name: Build And Deploy Code

on:
  push:
    branches:
      - "main"
      - "developer"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling the repo
        uses: actions/checkout@v2
      - name: Install Python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pytest
        run: |
          pip install pytest
          pytest tests -v